# Generated by Django 3.0.8 on 2021-05-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
